services:
    _defaults:
        autowire: true
        autoconfigure: true

    AtticConcepts\DatabaseSync\:
        resource: "../../*"
        exclude:
            - "../../{DependencyInjection,Resources}"

    AtticConcepts\DatabaseSync\Command\DatabaseSyncCommand:
        tags: ["console.command"]
