services:
    _defaults:
        autowire: true
        autoconfigure: true

    Barbieswimcrew\DatabaseSync\:
        resource: "../../*"
        exclude:
            - "../../{DependencyInjection,Resources}"
